spring:
  datasource:
    url: jdbc:sqlserver://databaserest.database.windows.net:1433;database=db1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: gabby
    password: Gabedailey200
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9090
